CREATE DATABASE Exercise1;
CREATE TABLE `exercise1`.`emp_1` (
  `EMP_NUM` CHAR(3) NOT NULL,
  `EMP_Lname` VARCHAR(15) NULL,
  `EMP_FNAME` VARCHAR(15) NULL,
  `EMP_INITIAL` CHAR(1) NULL,
  `EMP_HIREDATE` DATE NULL,
  `JOB_CODE` CHAR(3) NULL,
  PRIMARY KEY (`EMP_NUM`));
INSERT INTO EMP_1(EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('1', 'NIRGONA', 'IGARUS', 'G', '06-04-22', 502)
INSERT INTO EMP_1(EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('2', 'CHALANKA', 'MONTENEGRO', 'L', '11-03-22', 502)